steps:

# Build
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/techpay-repo/credit-api:test'
    - '.'

# Push
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/techpay-repo/credit-api:test'

# Deploy Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - credit-api
    - --image=us-central1-docker.pkg.dev/$PROJECT_ID/techpay-repo/credit-api:test
    - --region=us-central1
    - --platform=managed

    - --service-account=sa-credit-api@$PROJECT_ID.iam.gserviceaccount.com
    - --no-allow-unauthenticated
    - --set-secrets=CREDIT_API_KEY=credit-api-key:latest

    - --set-env-vars=REVISION_TAG=test

    - --min-instances=1
    - --vpc-connector=techpay-connector
    - --vpc-egress=all-traffic

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/techpay-repo/credit-api:test'
